#!/bin/sh
# Script to create a proper source tarball for kraft
# Klaas Freitag <freitag@kde.org>

VERSION=$1
if [ -z "$VERSION" ] ; then
  echo "Please specify the kraft version"
  exit
fi

echo "Creating kraft tarball version " $VERSION

svn export https://svn.kde.org/home/kde/trunk/playground/office/kraft
mv kraft kraft-$VERSION

cd kraft-$VERSION

echo "#MIN_CONFIG"  > configure.in.in
echo "AM_INIT_AUTOMAKE(kraft, $VERSION)" >> configure.in.in

echo src > subdirs
echo database >> subdirs
echo reports >> subdirs

. /etc/opt/kde3/common_options
update_admin

