# Find Asciidoctor - an Asciidoc converter to html
#
# ASCIIDOCTOR_FOUND
# ASCIIDOCTOR_EXECUTABLE

FIND_PROGRAM(ASCIIDOCTOR_EXECUTABLE asciidoctor)

MARK_AS_ADVANCED(ASCIIDOCTOR_EXECUTABLE)

IF (NOT ASCIIDOCTOR_EXECUTABLE)
  SET(ASCIIDOCTOR_FOUND "NO")
ELSE (NOT ASCIIDOCTOR_EXECUTABLE)
  SET(ASCIIDOCTOR_FOUND "YES")
ENDIF (NOT ASCIIDOCTOR_EXECUTABLE)


