/***************************************************************************
                          kangeview.h  -
                             -------------------
    begin                : Mit Dez 31 19:24:05 CET 2003
    copyright            : (C) 2003 by Klaas Freitag
    email                : freitag@kde.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KANGEVIEW_H
#define KANGEVIEW_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

// include files for Qt
#include <qwidget.h>
#include <qmap.h>

#include <kdialogbase.h>
#include <kabc/addressee.h>

#include "kraftdoc.h"

/** The KangeView class provides the view widget for the KangeApp instance.
 * The View instance inherits QWidget as a base class and represents
 * the view object of a KTMainWindow. As KangeView is part of the
 * docuement-view model, it needs a reference to the document object
 * connected with it by the KangeApp class to manipulate and display
 * the document structure provided by the KraftDoc class.
 *
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 0.4 code generation
 */
#include <qptrlist.h>

#include "positionviewwidget.h"

class QScrollView;
class DocHeaderEdit;
class DocFooterEdit;
class PositionViewWidget;
class DocPosition;
class QLabel;
class QResizeEvent;
class QSignalMapper;

class KangeViewScroll : public QScrollView
{
  Q_OBJECT
  
public:
  KangeViewScroll( QWidget* );
  ~KangeViewScroll() { }
  
  void resizeEvent( QResizeEvent* );
  void addChild( QWidget *child, int x=0, int y=0 );
  // the removeChild method is not virtual for scrollview, so
  // our own needs to be implemented.
  void kangeRemoveChild( PositionViewWidget *child );
private:
  QPtrList<PositionViewWidget> mWidgetList;
};



class KangeView : public KDialogBase
{
  Q_OBJECT
  public:
    /** Constructor for the main view */
    KangeView(QWidget *parent, const char *name=0);
    /** Destructor for the main view */
    ~KangeView();

    /** returns a pointer to the document connected to the view
    instance. Mind that this method requires a KangeApp instance as a
    parent * widget to get to the window document pointer by calling
    the KangeApp::getDocument() method.
     *
     * @see KangeApp#getDocument
     */
    KraftDoc *getDocument() const;

    /** contains the implementation for printing functionality */
    void print(QPrinter *pPrinter);

    void setup( DocGuardedPtr );
    

    typedef QMap<DocPositionBase*, PositionViewWidget*> PositionMap;

  public slots:
    void slotSelectAddress( KABC::Addressee contact = KABC::Addressee() );
    void redrawDocument( );
    void slotModifiedPositions();
    void slotModifiedHeader();
    void slotModifiedFooter();
    void slotAddPosition();
    void slotFocusPosition( int );
    
  protected slots:
    void slotOk();
    void slotCancel();
    void savePositions();
    void redrawDocPositions( );
    void done( int );
    void slotMovePositionUp( int );
    void slotMovePositionDown( int );
    void slotDeletePosition( int );
    void slotUnlockPosition(int);
    void slotLockPosition(int);
    void slotAboutToShow( QWidget* );  
    
  private:
    void setupDocHeaderView();
    void setupPositions();
    void setupFooter();
    void setupTextsView();
    
    QStringList generateLetterHead( KABC::Addressee adr );

    KangeViewScroll *m_positionScroll;
    DocHeaderEdit *m_headerEdit;
    DocFooterEdit *m_footerEdit;

    PositionMap mPositionWidgetMap;
    PositionViewWidgetList mPositionWidgetList;
    
    QString mContactUid;
    DocGuardedPtr m_doc;
    QSignalMapper *mDeleteMapper;
    QSignalMapper *mMoveUpMapper;
    QSignalMapper *mMoveDownMapper;
    QSignalMapper *mUnlockPositionMapper;
    QSignalMapper *mLockPositionMapper;
};

#endif // KANGEVIEW_H
