// This file is generated by kxml_compiler from kraftdoc.xsd.
// All changes you do to this file will be lost.
#ifndef KRAFTDOCUMENT_H
#define KRAFTDOCUMENT_H

#include <QDomElement>
#include <QString>
#include <QtXml/QXmlStreamWriter>

class 
{
  public:
    /**
      Parse XML object from DOM element.
     */
    static parseElement( const QDomElement &element, bool *ok );
    void writeElement( QXmlStreamWriter &xml );

};

class Kraftdocument
{
  public:
    void setVersion( const QString &v );
    QString version() const;
    void setLastModified( const QString &v );
    QString lastModified() const;
    void set( const  &v );
    () const;
    void set( const  &v );
    () const;
    void set( const  &v );
    () const;
    void set( const  &v );
    () const;
    /**
      Parse XML object from DOM element.
     */
    static Kraftdocument parseElement( const QDomElement &element, bool *ok );
    void writeElement( QXmlStreamWriter &xml );
    static Kraftdocument parseFile( const QString &filename, bool *ok );
    static Kraftdocument parseString( const QString &xml, bool *ok );
    bool writeFile( const QString &filename );

  private:
    QString mVersion;
    QString mLastModified;
     mUndefined;
     mUndefined;
     mUndefined;
     mUndefined;
};

#endif
