name: Qt6 + Clazy

on:
  push:
    branches: [portqt6_1]
  pull_request:

jobs:
  clazy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt 6 and Clazy
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev clang cmake
          git config --global --add safe.directory /__w/kraft/kraft
          git clone https://invent.kde.org/sdk/clazy.git
          cd clazy && mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          sudo make install

      - name: Configure with Clazy
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=clazy

      - name: Compile with Clazy
        run: |
          cd build
          make -j$(nproc)

